version: '3'

services:

  embeddia-redis:
    container_name: embeddia-redis
    image: redis:latest

  embeddia-postgres:
    image: postgres:12-alpine
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/
    env_file:
      - ./env.hatespeech

  embeddia-hsd:
    container_name: embeddia-hsd
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-hsd:latest
    build:
      context: ./modules/embeddia-hsd/services/web
      dockerfile: Dockerfile
    ports:
      - "5000"
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./data/:/usr/src/app/project/models
    env_file:
      - ./env.hatespeech
    depends_on:
      - embeddia-postgres

  embeddia-nlg:
    container_name: embeddia-nlg
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-nlg:latest
    build:
      context: ./modules/embeddia-nlg
      dockerfile: Dockerfile
    ports:
      - "8080"
    volumes:
      - ./data:/app/data

  embeddia-kwe:
    container_name: embeddia-kwe
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-kwe:latest
    build:
      context: ./modules/embeddia-kwe/services/web
      dockerfile: Dockerfile
    ports:
      - "5000"
    env_file:
      - ./env.keyword
    command: python -u manage.py run -h 0.0.0.0

  # embeddia-ner:
  #   container_name: embeddia-ner
  #   image: docker.texta.ee/texta/embeddia-toolkit/embeddia-ner:latest
  #   build:
  #     context: ./modules/embeddia-ner/services/web
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5004:5000"
  #   env_file:
  #     - ./env.ner
  #   command: python -u manage.py run -h 0.0.0.0
  #   depends_on:
  #     - embeddia-ner-worker

  # embeddia-ner-worker:
  #   build:
  #     context: ./modules/embeddia-ner/services/celery-queue
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./env.ner
  #   ports:
  #    - "5555:5555"
  #   volumes:
  #     - ./data/celery-flower_data:/persistent
  #   depends_on:
  #     - embeddia-redis

  # ner:
  #   build:
  #       context: ./modules/embeddia-ner/services/ner-service
  #       dockerfile: Dockerfile
  #   env_file:
  #     - ./env.ner
  #   volumes:
  #     - ./data/ner-data:/data
  #   expose:
  #     - "18861"

  embeddia-rest-front:
    container_name: embeddia-rest-front
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-front:latest
    ports:
      - "4200:80"
    env_file:
      - ./env.embeddia
    depends_on:
      - embeddia-rest

  embeddia-rest:
    container_name: embeddia-rest
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-rest:latest
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    env_file:
      - ./env.embeddia
    volumes:
      - ./data:/var/embeddia-rest/data
      - ./src:/var/embeddia-rest/src
    depends_on:
      - embeddia-kwe
      - embeddia-nlg
      - embeddia-hsd
