version: '3'

services:

  # embeddia-redis:
  #   container_name: embeddia-redis
  #   image: redis:latest

  embeddia-postgres:
    image: postgres:12-alpine
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/
    env_file:
      - ./env.hatespeech

  embeddia-hsd:
    container_name: embeddia-hsd
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-hsd:latest
    build:
      context: ./modules/embeddia-hsd/services/web
      dockerfile: Dockerfile
    ports:
      - "5000"
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./data/:/usr/src/app/project/models
    env_file:
      - ./env.hatespeech
    depends_on:
      - embeddia-postgres

  embeddia-nlg:
    container_name: embeddia-nlg
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-nlg:latest
    build:
      context: ./modules/embeddia-nlg
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    volumes:
      - ./data:/app/data

  embeddia-kwe:
    container_name: embeddia-kwe
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-kwe:latest
    build:
      context: ./modules/embeddia-kwe/services/web
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    env_file:
      - ./env.keyword
    command: python -u manage.py run -h 0.0.0.0

  # embeddia-ner:
  #   container_name: embeddia-ner
  #   image: docker.texta.ee/texta/embeddia-toolkit/embeddia-ner:latest
  #   build:
  #     context: ./modules/embeddia-ner/services/web
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5004:5000"
  #   env_file:
  #     - ./env.ner
  #   command: python -u manage.py run -h 0.0.0.0

  embeddia-rest:
    container_name: embeddia-rest
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-rest:latest
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    env_file:
      - ./env.embeddia
    volumes:
      - ./data:/var/embeddia-rest/data
    depends_on:
      - embeddia-kwe
      - embeddia-nlg
      - embeddia-hsd
