version: '3'

services:

  embeddia-postgres:
    image: postgres:12-alpine
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/
    env_file:
      - ./env.hatespeech

  embeddia-hsd:
    image: embeddia-hsd:latest
    ports:
      - 5001:5000
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./data/:/data/
    env_file:
      - ./env.hatespeech
    depends_on:
      - embeddia-postgres

 # embeddia-nlg:
 #   image: embeddia-nlg:latest
 #   ports:
 #     - 5002:8080
 #   volumes:
 #     - ./data:/app/data

  embeddia-kwe:
    image: embeddia-kwe:latest
    ports:
      - 5003:5000
    env_file:
      - ./env.keyword
    command: python -u manage.py run -h 0.0.0.0

#  embeddia-rest:
#    image: embeddia-rest:latest
#    ports:
#      - 80:80
#    env_file:
#      - ./env.embeddia
#    depends_on:
#      - embeddia-kwe
#      - embeddia-hsd
