version: '3'

services:

  embeddia-postgres:
    image: postgres:12-alpine
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/
    env_file:
      - ./env.hatespeech

  embeddia-redis:
    container_name: embeddia-redis
    image: redis
    ports:
      - 6379
    restart: always

  embeddia-nlg:
    container_name: embeddia-nlg
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-nlg:latest
    ports:
      - 5555:8080
    volumes:
      - ./data:/app/data

  embeddia-hsd:
    container_name: embeddia-hsd
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-hsd:latest
    ports:
      - 5000
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./data/:/usr/src/app/project/models
    env_file:
      - ./env.hatespeech
    depends_on:
      - embeddia-postgres

  embeddia-kwe-et:
    container_name: embeddia-kwe-et
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-kwe-et:latest
    ports:
      - 5000
    env_file:
      - ./env.keyword
    command: python -u manage.py run -h 0.0.0.0

  embeddia-kwe-hr:
    container_name: embeddia-kwe-hr
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-kwe-hr:latest
    ports:
      - 5000
    env_file:
      - ./env.keyword
    command: python -u manage.py run -h 0.0.0.0

  embeddia-kwe-lv:
    container_name: embeddia-kwe-lv
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-kwe-lv:latest
    ports:
      - 5000
    env_file:
      - ./env.keyword
    command: python -u manage.py run -h 0.0.0.0

  embeddia-ner:
    container_name: embeddia-ner
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-ner:latest
    ports:
      - 5000
    env_file:
      - ./env.ner
    command: python -u manage.py run -h 0.0.0.0
    depends_on:
      - embeddia-ner-worker

  embeddia-ner-worker:
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-ner-worker:latest
    env_file:
      - ./env.ner
    ports:
     - 5555
    volumes:
      - ./data/celery-flower_data:/persistent
    depends_on:
      - embeddia-redis

  ner:
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-ner-service:latest
    env_file:
      - ./env.ner
    volumes:
      - ./data/ner-data:/data
    #  - ./data/ner-model-data:/ner_service/NER/models
    expose:
      - 18861

  embeddia-rest:
    container_name: embeddia-rest
    image: docker.texta.ee/texta/embeddia-toolkit/embeddia-rest:latest
    ports:
     - 8090:80
    env_file:
     - ./env.embeddia
    volumes:
      - ./data:/var/embeddia-rest/data
      - ./src:/var/embeddia-rest/src
    depends_on:
      - embeddia-redis
      - embeddia-kwe-hr
      - embeddia-kwe-et
      - embeddia-hsd
      - embeddia-ner
