name: embeddia-rest

channels:
  - conda-forge
  - anaconda
  - bioconda
  - pytorch

dependencies:
  - python=3.8
  - pip
  - supervisor
  - uwsgi
  - psutil
  - nginx
  - pip:
    - django==2.1.*
    - django-cors-headers
    - djangorestframework==3.9.*
    - requests
    - whitenoise
    - texta-mlp==1.15.*
    - celery==4.*
    - redis==3.*
