name: embeddia-rest

channels:
  - conda-forge
  - anaconda
  - bioconda
  - pytorch

dependencies:
  - python=3.6
  - pip
  - supervisor
  - uwsgi
  - pip:
    - django==2.1.*
    - django-cors-headers
    - djangorestframework==3.9.*
    - requests
    - whitenoise
    - psutil
    - git+https://mlp:KdP4zzGu2dz9WMtKYozv@git.texta.ee/texta/texta-mlp-python
